use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=src/message/catalog.rs");
    println!("cargo:rerun-if-changed=src/message/legacy_aliases.txt");

    let catalog = fs::read_to_string("src/message/catalog.rs").expect("read message catalog");
    let variants = catalog
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            let rest = line.strip_prefix('(')?;
            let (variant, rest) = rest.split_once(',')?;
            rest.trim_start()
                .starts_with("0x")
                .then(|| variant.to_owned())
        })
        .collect::<HashSet<_>>();

    let aliases = fs::read_to_string("src/message/legacy_aliases.txt")
        .expect("read legacy message alias spellings");
    let mut generated =
        String::from("// @generated by build.rs from message/catalog.rs; do not edit.\n");
    let mut pairs = String::from(
        "\n#[cfg(test)]\npub(crate) const LEGACY_ALIAS_CATALOG_PAIRS: &[(u32, u32)] = &[\n",
    );
    for (line_number, line) in aliases.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (variant, alias) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid legacy alias on line {}", line_number + 1));
        assert!(
            variants.contains(variant),
            "unknown catalog variant {variant}"
        );
        generated.push_str(&format!(
            "pub const {alias}: u32 = super::catalog::MessageId::{variant}.wire_value();\n"
        ));
        pairs.push_str(&format!(
            "    ({alias}, super::catalog::MessageId::{variant}.wire_value()),\n"
        ));
    }
    pairs.push_str("];\n");
    generated.push_str(&pairs);

    let output =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("legacy_message_ids.rs");
    fs::write(output, generated).expect("write generated legacy message aliases");
}
