[general]
bind = 45.154.28.21:2000
advertised_address = 45.154.28.21
server_name = sip.anderstorpsfestivalen.se
keepalive = 60
firstdigittimeout = 10
interdigit_timeout_ms = 5000
echocancel = yes
silencesuppression = no
earlyrtp = yes
directrtp = no
remotehangup_tone = 0

[7961-common-softkeys]
type = softkey_profile
on_hook = redial, new_call, forward_all, pickup, group_pickup, dnd
connected = hold, end_call, transfer, conference, park, private
on_hold = resume, new_call, end_call, transfer, conference_list, select, direct_transfer
ring_in = answer, end_call
off_hook = redial, end_call
connected_transfer = hold, end_call, transfer, conference, park, select, direct_transfer
digits_following = backspace, end_call, dial
connected_conference = hold, conference_list, join, end_call
ring_out = callback, end_call
off_hook_feature = resume, new_call, end_call
in_use_hint = barge
on_hook_stealable = intercept, new_call
hold_conference = resume, new_call, end_call
empty =

[SEP00A1B2C3D4E5]
type = device
description = 7961G
softkey_profile = 7961-common-softkeys
nat = auto
force_dtmfmode = auto
directrtp = no
earlyrtp = yes
cfwdall = yes
cfwdbusy = yes
cfwdnoanswer = yes
dnd_feature = yes
dnd = off
privacy_feature = yes
privacy = no
park = yes
conf_allow = yes
useRedialMenu = no
button = line, 1006, label=1006, caller_name=Wbergs Desk, caller_number=1006, ring=normal, privacy=no
button = speed_dial, fozzie, 2001
button = speed_dial, coral, 3001
button = speed_dial, alexfoo, 4001
button = speed_dial, SIPCORD, 9000
button = speed_dial, Conference Room, 9002

[1006]
type = line
label = 1006
context = internal
callerid = "Wbergs Desk" <1006>
incominglimit = 6
directed_pickup = yes
pickup_mode_answer = yes
parkinglot = default
